name = "idxgp"
account_id = "<your-cloudflare-account-id>"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "idxgp-db"
database_id = "b3e8556b-ca6e-46f3-b399-2f836ebb396e"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "idxgp-db"
database_id = "b3e8556b-ca6e-46f3-b399-2f836ebb396e"
